language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=/opt/devkitpro    
    - DEVKITARM=/opt/devkitpro/devkitARM
    
cache:
  directories:
    - "$HOME/.local"
    - "$DEVKITPRO"

before_install:
  - curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
  - sudo apt-get install -y p7zip-full

install:
  - sudo dpkg -i pacman.deb
  - sudo dkp-pacman -Sy
  - sudo dkp-pacman -S devkitARM general-tools dstools ndstool libnds libfat-nds grit mmutil --noconfirm
  - git clone https://github.com/RocketRobz/libnds.git
  - cd libnds/
  - sudo make install
  - cd ..
  - sudo rm -r libnds/
  - 
  - git clone https://github.com/RocketRobz/libnds.git
  - cd libnds/
  - sudo make install
  - cd ..
  - sudo rm -r libnds/
  - 
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

script:
  - export COMMIT_TAG="$(git log --format=%h -1)"
  - export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
  - cd romsel_aktheme/
  - make
  - cd ../
  - 7z x libnds.7z
  - sudo cp -r libnds/* /opt/devkitpro/libnds/
  - make package
  - mv 7zfile/ TWiLightMenu/
  - 7z a TWiLightMenu.7z TWiLightMenu/
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

before_deploy:
  - git config --local user.name "TWLBot"
  - git config credential.username $GITHUB_TOKEN
  - git clone https://github.com/TWLBot/Builds.git
  - cd Builds/
  - cp ../TWiLightMenu.7z TWiLightMenu.7z
  - git stage .
  - git commit -m "TWiLight Menu | $COMMIT_TAG"
  - git push origin master
  # - export CURRENT_DATE=$(date +'%Y%m%d-%H%M%S')
  # - git tag v$CURRENT_DATE
  - git tag v$GITHUB_COMMIT

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file: TWiLightMenu.7z
  skip_cleanup: true
  repo: TWLBot/Builds
  prerelease: true
  name: TWiLightMenu | $COMMIT_TAG
  body: $COMMIT_MESSAGE
