language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=/opt/devkitpro    
    - DEVKITARM=/opt/devkitpro/devkitARM
    
cache:
  directories:
    - "$HOME/.local"
    - "$DEVKITPRO"

before_install:
  - curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
  - sudo apt-get install -y p7zip-full

install:
  - sudo dpkg -i pacman.deb
  - sudo dkp-pacman -Sy
  - sudo dkp-pacman -S devkitARM general-tools dstools ndstool libnds libfat-nds grit mmutil --noconfirm
  - git clone https://github.com/RocketRobz/libnds.git
  - cd libnds/
  - sudo make install
  - cd ..
  - sudo rm -r libnds/
  - 
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

script:
  - export COMMIT_TAG="$(git log --format=%h -1)"
  - export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
  - cd romsel_aktheme/
  - make
  - cd ../
  - 7z x libnds.7z
  - sudo cp -r libnds/* /opt/devkitpro/libnds/
  - make
  - mkdir 7zfile/DSi\ -\ CFW\ users/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/title/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/title/00030004/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/title/00030004/53524c41/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/title/00030004/53524c41/content/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/title/00030015/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/title/00030015/534c524e/
  - mkdir 7zfile/DSi\ -\ CFW\ users/SDNAND\ root/title/00030015/534c524e/content/
  - cp "booter/booter.nds" "7zfile/BOOT.NDS"
  - cp "booter/booter.nds" "7zfile/DSi - CFW users/SDNAND root/title/00030004/53524c41/content/00000000.app"
  - cp "booter_fc/booter_fc.nds" "7zfile/BOOT_FC.NDS"
  - cp "mainmenu/mainmenu.nds" "7zfile/_nds/TWiLightMenu/mainmenu.srldr"
  - cp "romsel_aktheme/romsel_aktheme.nds" "7zfile/_nds/TWiLightMenu/akmenu.srldr"
  - cp "romsel_dsimenutheme/romsel_dsimenutheme.nds" "7zfile/_nds/TWiLightMenu/dsimenu.srldr"
  - cp "romsel_r4theme/romsel_r4theme.nds" "7zfile/_nds/TWiLightMenu/r4menu.srldr"
  - cp "rungame/rungame.nds" "7zfile/DSi - CFW users/SDNAND root/title/00030015/534c524e/content/00000000.app"
  - cp "settings/settings.nds" "7zfile/_nds/TWiLightMenu/settings.srldr"
  - cp "slot1launch/slot1launch.nds" "7zfile/_nds/TWiLightMenu/slot1launch.srldr"
  - cp "title/title.nds" "7zfile/_nds/TWiLightMenu/main.srldr"
  - mv 7zfile/ TWiLightMenu/
  - 7z a TWiLightMenu.7z TWiLightMenu/
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp

before_deploy:
  - git config --local user.name "TWLBot"
  - export CURRENT_DATE=$(date +'%Y%m%d-%H%M%S')
  - git tag v$CURRENT_DATE

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file: TWiLightMenu.7z
  skip_cleanup: true
  repo: Epicpk11/TWLBuilds-test
  prerelease: true
  name: TWiLightMenu | $COMMIT_TAG
  body: $COMMIT_MESSAGE
