# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'
strategy:
  matrix:
    set_env_to_one:
      object: DEVKITPRO=/opt/devkitpro 
    set_env_to_two:
      object: DEVKITARM=/opt/devkitpro/devkitARM
    set_env_to_three:
      object: docker

steps:
- script: |
    sudo dpkg -i pacman.deb
    sudo dkp-pacman -Sy
    sudo dkp-pacman -S devkitARM general-tools dstools ndstool libnds libfat-nds grit mmutil --noconfirm
    export DEVKITPRO=/opt/devkitpro
    export DEVKITARM=${DEVKITPRO}/devkitARM

    export COMMIT_TAG="$(git log --format=%h -1)"
    export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
    docker run --rm -t -i -v "$BUILD_SOURCESDIRECTORY:/data" twilightmenu make package
    mv 7zfile/ TWiLightMenu/
    7z a TWiLightMenu.7z TWiLightMenu/