"project_id_env": "TWILIGHT_CROWDIN_ID"
"api_token_env": "CROWDIN_TOKEN"
preserve_hierarchy: true

files:
  - source: /romsel_aktheme/nitrofiles/language/lang_en/language.ini
    translation: /romsel_aktheme/nitrofiles/language/lang_%two_letters_code%/language.ini
  - source: /romsel_dsimenutheme/nitrofiles/languages/en/*
    translation: /romsel_dsimenutheme/nitrofiles/languages/%two_letters_code%/%original_file_name%
  - source: /settings/nitrofiles/languages/en/*
    translation: /settings/nitrofiles/languages/%two_letters_code%/%original_file_name%
